"""add business tables

Revision ID: 0002_business_tables
Revises: 0001_initial
Create Date: 2026-09-23 20:06:12.011904
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002_business_tables'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('schedule', sa.String(length=128), nullable=False),
    sa.Column('target_system', sa.String(length=128), nullable=False),
    sa.Column('backup_type', sa.String(length=16), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_jobs_name'), 'backup_jobs', ['name'], unique=True)
    op.create_index(op.f('ix_backup_jobs_status'), 'backup_jobs', ['status'], unique=False)
    op.create_table('restore_drills',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('backup_job_id', sa.String(length=64), nullable=False),
    sa.Column('planned_date', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restore_drills_backup_job_id'), 'restore_drills', ['backup_job_id'], unique=False)
    op.create_index(op.f('ix_restore_drills_name'), 'restore_drills', ['name'], unique=False)
    op.create_index(op.f('ix_restore_drills_status'), 'restore_drills', ['status'], unique=False)
    op.create_table('retention_policies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('keep_count', sa.Integer(), nullable=False),
    sa.Column('archive_after_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_policies_name'), 'retention_policies', ['name'], unique=True)
    op.create_index(op.f('ix_retention_policies_status'), 'retention_policies', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retention_policies_status'), table_name='retention_policies')
    op.drop_index(op.f('ix_retention_policies_name'), table_name='retention_policies')
    op.drop_table('retention_policies')
    op.drop_index(op.f('ix_restore_drills_status'), table_name='restore_drills')
    op.drop_index(op.f('ix_restore_drills_name'), table_name='restore_drills')
    op.drop_index(op.f('ix_restore_drills_backup_job_id'), table_name='restore_drills')
    op.drop_table('restore_drills')
    op.drop_index(op.f('ix_backup_jobs_status'), table_name='backup_jobs')
    op.drop_index(op.f('ix_backup_jobs_name'), table_name='backup_jobs')
    op.drop_table('backup_jobs')
    # ### end Alembic commands ###
